version: '3.8'
services:
  db:
    ports:
      - '5432:5432'
    image: postgres:15.2
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: radiation
      POSTGRES_URL: jdbc:postgresql://localhost:5432/radiation
      POSTGRES_HOST_AUTH_METHOD: trust
